# Generated by Django 3.1 on 2020-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=75)),
                ('writer', models.CharField(max_length=50)),
            ],
        ),
    ]
